apiVersion: v1
kind: Namespace
metadata:
  name: streamhub-prod
  labels:
    app.kubernetes.io/part-of: streamhub
    streamhub.io/env: prod
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/enforce-version: latest
