apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - gateway.yaml
  - httproute-http-redirect.yaml
  - httproute-api.yaml
  - httproute-bo-api.yaml
  - httproute-web.yaml
  - healthcheckpolicy.yaml
  - backendpolicy-cloud-armor.yaml
