apiVersion: v1
kind: ServiceAccount
metadata:
  name: bo-api
  labels:
    app.kubernetes.io/name: bo-api
    app.kubernetes.io/part-of: streamhub
  annotations:
    iam.gke.io/gcp-service-account: PLACEHOLDER
