FROM nginx:alpine
COPY web/broadcaster /usr/share/nginx/html/broadcaster
COPY web/viewer /usr/share/nginx/html/viewer
COPY web/admin /usr/share/nginx/html/admin
COPY deploy/web/nginx.conf /etc/nginx/conf.d/default.conf
