server {
    listen 8080;

    location /broadcaster/ {
        alias /usr/share/nginx/html/broadcaster/;
        try_files $uri $uri/ /broadcaster/index.html;
    }

    location /viewer/ {
        alias /usr/share/nginx/html/viewer/;
        try_files $uri $uri/ /viewer/index.html;
    }

    location /admin/ {
        alias /usr/share/nginx/html/admin/;
        try_files $uri $uri/ /admin/index.html;
    }

}
