apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: gcp-secret-manager
spec:
  provider:
    gcpsm:
      projectID: PROJECT_ID
      auth:
        workloadIdentity:
          clusterLocation: asia-east1
          clusterName: streamhub-prod
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
