apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: api-env
spec:
  data:
    - secretKey: database_url
      remoteRef:
        key: streamhub-prod-api-database-url
    - secretKey: redis_url
      remoteRef:
        key: streamhub-prod-redis-url
    - secretKey: jwt_secret
      remoteRef:
        key: streamhub-prod-jwt-secret
    - secretKey: gcs_bucket
      remoteRef:
        key: streamhub-prod-gcs-bucket
    - secretKey: transcoder_project_id
      remoteRef:
        key: streamhub-prod-transcoder-project-id
    - secretKey: pubsub_verify_token
      remoteRef:
        key: streamhub-prod-pubsub-verify-token
