apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: bo-api-env
spec:
  data:
    - secretKey: database_url
      remoteRef:
        key: streamhub-prod-api-database-url
    - secretKey: redis_url
      remoteRef:
        key: streamhub-prod-redis-url
    - secretKey: jwt_secret
      remoteRef:
        key: streamhub-prod-jwt-secret
